version: '3.9'
services:
  mongo: 
      image: mongo:5
      restart: always
      ports:
        - "${EXPOSE_DB_PORT}:5432"
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      volumes:
        - postgres-data:/var/lib/postgresql/data
  app:
    depends_on:
      postgres:
        condition: service_started 
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
volumes:
  postgres-data:
