version: '3.9'
services:
  mongo: 
      image: mongo:5
      restart: always
      ports:
        - "${DOCKER_DB_PORT}:27017"
      environment:
        MONGODB_DATABASE: ${DB_NAME}
      volumes:
        - mongo-data:/data/db
volumes:
  mongo-data:
