version: "3.9"
services:
  mongo: 
      image: mongo:6
      restart: always
      ports:
        - "${DOCKER_DB_PORT}:27017"
      environment:
        MONGODB_DATABASE: ${DB_NAME}
      volumes:
        - mongo-data:/data/db
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mongo
volumes:
  mongo-data:


